// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ_AeJweJxjPmMLhW5add4MdrPnWO050E',
    appId: '1:589941651652:android:73cced8ca75023c4323191',
    messagingSenderId: '589941651652',
    projectId: 'afc-arsenal',
    databaseURL: 'https://afc-arsenal-default-rtdb.firebaseio.com',
    storageBucket: 'afc-arsenal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RJDfEnkD__Xq4w6clS39NyMtxuwJoto',
    appId: '1:589941651652:ios:8f8cd9a8d839247c323191',
    messagingSenderId: '589941651652',
    projectId: 'afc-arsenal',
    databaseURL: 'https://afc-arsenal-default-rtdb.firebaseio.com',
    storageBucket: 'afc-arsenal.appspot.com',
    androidClientId: '589941651652-9r1ul95q4bcuh10pij09p5eovfic34ea.apps.googleusercontent.com',
    iosClientId: '589941651652-4f4qp75176mj0l3i936jsvm6ba5uhjsn.apps.googleusercontent.com',
    iosBundleId: 'com.ntchung.arsenalafc',
  );
}
